Repository JuliaDocs/DocumenterCitations.jl, pull requests merged in 2024-11, with the labels that each got.

#81 Pin BibInternal to v0.3.6
  .github/workflows/ci.yml
  Project.toml
Labels: bug, no changelog

#79 Pass extra keyword arguments to format_names
  src/labeled_styles_utils.jl
Labels: enhancement

#82 Un-escape TeX before generating name initials
  docs/src/refs.bib
  src/formatting.jl
  test/test_formatting.jl
  test/test_formatting/issue78.bib
  test/test_tex_to_markdown.jl
Labels: bug

#84 Release 1.3.5
  NEWS.md
  Project.toml
Labels: no changelog
